// DOM element registry — every control and readout the app touches.

const $ = (id) => document.getElementById(id);
const els = {
  seed: $('seed'),
  randomSeed: $('randomSeed'),
  earthPreset: $('earthPreset'),
  renderMode: $('renderMode'),
  quality: $('quality'),
  planetGLCanvas: $('planetGL'),
  terraformSection: $('terraformSection'),
  appearanceSection: $('appearanceSection'),
  gradImage: $('gradImage'),
  gradIntensity: $('gradIntensity'), gradIntensityVal: $('gradIntensityVal'),
  gradScale: $('gradScale'), gradScaleVal: $('gradScaleVal'),
  gradStatus: $('gradStatus'),
  gradTargets: $('gradTargets'),
  gtWaterEn: $('gtWaterEn'), gtWaterLo: $('gtWaterLo'), gtWaterHi: $('gtWaterHi'),
  gtLandEn: $('gtLandEn'), gtLandLo: $('gtLandLo'), gtLandHi: $('gtLandHi'),
  gtVegEn: $('gtVegEn'), gtVegLo: $('gtVegLo'), gtVegHi: $('gtVegHi'),
  gtIceEn: $('gtIceEn'), gtIceLo: $('gtIceLo'), gtIceHi: $('gtIceHi'),
  gradClear: $('gradClear'),
  palWater: $('palWater'), palLand: $('palLand'), palVeg: $('palVeg'),
  palRock: $('palRock'), palIce: $('palIce'), palAtmos: $('palAtmos'), palCloud: $('palCloud'),
  palReset: $('palReset'),
  lblWater: $('lblWater'), lblLand: $('lblLand'), lblVeg: $('lblVeg'), lblRock: $('lblRock'), lblIce: $('lblIce'),
  tfSea: $('tfSea'), tfSeaVal: $('tfSeaVal'),
  tfVeg: $('tfVeg'), tfVegVal: $('tfVegVal'),
  tfIce: $('tfIce'), tfIceVal: $('tfIceVal'),
  tfCloud: $('tfCloud'), tfCloudVal: $('tfCloudVal'),
  tfCloudCover: $('tfCloudCover'), tfCloudCoverVal: $('tfCloudCoverVal'),
  tfCloudAltLow: $('tfCloudAltLow'), tfCloudAmtLow: $('tfCloudAmtLow'),
  tfCloudAltMid: $('tfCloudAltMid'), tfCloudAmtMid: $('tfCloudAmtMid'),
  tfCloudAltHigh: $('tfCloudAltHigh'), tfCloudAmtHigh: $('tfCloudAmtHigh'),
  tfCloudScatter: $('tfCloudScatter'), tfCloudScatterVal: $('tfCloudScatterVal'),
  tfCloudFlow: $('tfCloudFlow'), tfCloudFlowVal: $('tfCloudFlowVal'),
  tfCloudSeed: $('tfCloudSeed'),
  tfAtmo: $('tfAtmo'), tfAtmoVal: $('tfAtmoVal'),
  tfAtmoDensity: $('tfAtmoDensity'), tfAtmoDensityVal: $('tfAtmoDensityVal'),
  tfEvolve: $('tfEvolve'), tfEvolveVal: $('tfEvolveVal'),
  tfEvolveScale: $('tfEvolveScale'), tfEvolveScaleVal: $('tfEvolveScaleVal'),
  tfSnow: $('tfSnow'), tfSnowVal: $('tfSnowVal'),
  tfVortex: $('tfVortex'), tfVortexVal: $('tfVortexVal'),
  tfChurn: $('tfChurn'), tfChurnVal: $('tfChurnVal'),
  tfGasDensity: $('tfGasDensity'), tfGasDensityVal: $('tfGasDensityVal'),
  tfGasScale: $('tfGasScale'), tfGasScaleVal: $('tfGasScaleVal'),
  tfGasTurb: $('tfGasTurb'), tfGasTurbVal: $('tfGasTurbVal'),
  tfGasDetail: $('tfGasDetail'), tfGasDetailVal: $('tfGasDetailVal'),
  tfEmission: $('tfEmission'), tfEmissionVal: $('tfEmissionVal'),
  tfAurora: $('tfAurora'), tfAuroraVal: $('tfAuroraVal'),
  tfRivers: $('tfRivers'), tfRiversVal: $('tfRiversVal'),
  tfErosion: $('tfErosion'), tfErosionVal: $('tfErosionVal'),
  tfDetail: $('tfDetail'), tfDetailVal: $('tfDetailVal'),
  tfIterations: $('tfIterations'), tfIterationsVal: $('tfIterationsVal'),
  tfPresetDead: $('tfPresetDead'),
  tfPresetFlood: $('tfPresetFlood'),
  tfPresetEden: $('tfPresetEden'),
  tfPresetReset: $('tfPresetReset'),
  animExportSection: $('animExportSection'),
  animFormat: $('animFormat'),
  animFrames: $('animFrames'), animFramesVal: $('animFramesVal'),
  animRes: $('animRes'),
  animAlpha: $('animAlpha'),
  exportAnim: $('exportAnim'),
  animProgress: $('animProgress'),
  mapExportSection: $('mapExportSection'),
  mapGround: $('mapGround'), mapVeg: $('mapVeg'), mapSnow: $('mapSnow'),
  mapWater: $('mapWater'), mapClouds: $('mapClouds'), mapMask: $('mapMask'),
  mapRes: $('mapRes'), exportMap: $('exportMap'), mapProgress: $('mapProgress'),
  planetType: $('planetType'),
  size: $('size'),
  sizeVal: $('sizeVal'),
  atmosphere: $('atmosphere'),
  pixelScale: $('pixelScale'),
  pixelVal: $('pixelVal'),
  antialias: $('antialias'),
  genRes: $('genRes'),
  previewMode: $('previewMode'),
  fxBloom: $('fxBloom'), fxBloomVal: $('fxBloomVal'),
  fxChroma: $('fxChroma'), fxChromaVal: $('fxChromaVal'),
  fxGrain: $('fxGrain'), fxGrainVal: $('fxGrainVal'),
  autoRotate: $('autoRotate'),
  displacement: $('displacement'),
  displacementVal: $('displacementVal'),
  sunAzimuth: $('sunAzimuth'),
  sunAzimuthVal: $('sunAzimuthVal'),
  sunElevation: $('sunElevation'),
  sunElevationVal: $('sunElevationVal'),
  viewTilt: $('viewTilt'),
  viewTiltVal: $('viewTiltVal'),
  sunIntensity: $('sunIntensity'),
  sunIntensityVal: $('sunIntensityVal'),
  sunHue: $('sunHue'),
  sunHueVal: $('sunHueVal'),
  generate: $('generate'),
  loading: $('loading'),
  status: $('status'),
  meta: $('meta'),

  designation: $('designation'),
  designationClass: $('designationClass'),
  dRadius: $('dRadius'),
  dMass: $('dMass'),
  dGrav: $('dGrav'),
  dDay: $('dDay'),
  dAlbedo: $('dAlbedo'),
  dTemp: $('dTemp'),
  dPressure: $('dPressure'),
  compBar: $('compBar'),
  compLegend: $('compLegend'),
  features: $('features'),
  resources: $('resources'),
  exportCard: $('exportCard'),
  dHab: $('dHab'),
  dWater: $('dWater'),

  vpDesignation: $('vpDesignation'),
  vpClass: $('vpClass'),
  vpFrame: $('vpFrame'),
  vpRender: $('vpRender'),

  starsCanvas: $('stars'),
  planetCanvas: $('planet'),
};

export { $, els };
