// DOM element registry — every control and readout the app touches.

const $ = (id) => document.getElementById(id);
const els = {
  seed: $('seed'),
  randomSeed: $('randomSeed'),
  earthPreset: $('earthPreset'),
  renderMode: $('renderMode'),
  quality: $('quality'),
  planetGLCanvas: $('planetGL'),
  terraformSection: $('terraformSection'),
  tfSea: $('tfSea'), tfSeaVal: $('tfSeaVal'),
  tfVeg: $('tfVeg'), tfVegVal: $('tfVegVal'),
  tfIce: $('tfIce'), tfIceVal: $('tfIceVal'),
  tfCloud: $('tfCloud'), tfCloudVal: $('tfCloudVal'),
  tfAtmo: $('tfAtmo'), tfAtmoVal: $('tfAtmoVal'),
  tfEvolve: $('tfEvolve'), tfEvolveVal: $('tfEvolveVal'),
  tfSnow: $('tfSnow'), tfSnowVal: $('tfSnowVal'),
  tfVortex: $('tfVortex'), tfVortexVal: $('tfVortexVal'),
  tfChurn: $('tfChurn'), tfChurnVal: $('tfChurnVal'),
  tfGasDensity: $('tfGasDensity'), tfGasDensityVal: $('tfGasDensityVal'),
  tfEmission: $('tfEmission'), tfEmissionVal: $('tfEmissionVal'),
  tfAurora: $('tfAurora'), tfAuroraVal: $('tfAuroraVal'),
  tfRivers: $('tfRivers'), tfRiversVal: $('tfRiversVal'),
  tfErosion: $('tfErosion'), tfErosionVal: $('tfErosionVal'),
  tfIterations: $('tfIterations'), tfIterationsVal: $('tfIterationsVal'),
  tfProcClouds: $('tfProcClouds'),
  tfPresetDead: $('tfPresetDead'),
  tfPresetFlood: $('tfPresetFlood'),
  tfPresetEden: $('tfPresetEden'),
  tfPresetReset: $('tfPresetReset'),
  animExportSection: $('animExportSection'),
  animFormat: $('animFormat'),
  animFrames: $('animFrames'), animFramesVal: $('animFramesVal'),
  animRes: $('animRes'),
  animAlpha: $('animAlpha'),
  exportAnim: $('exportAnim'),
  animProgress: $('animProgress'),
  planetType: $('planetType'),
  size: $('size'),
  sizeVal: $('sizeVal'),
  atmosphere: $('atmosphere'),
  pixelScale: $('pixelScale'),
  pixelVal: $('pixelVal'),
  autoRotate: $('autoRotate'),
  displacement: $('displacement'),
  displacementVal: $('displacementVal'),
  sunAzimuth: $('sunAzimuth'),
  sunAzimuthVal: $('sunAzimuthVal'),
  sunElevation: $('sunElevation'),
  sunElevationVal: $('sunElevationVal'),
  viewTilt: $('viewTilt'),
  viewTiltVal: $('viewTiltVal'),
  sunIntensity: $('sunIntensity'),
  sunIntensityVal: $('sunIntensityVal'),
  sunHue: $('sunHue'),
  sunHueVal: $('sunHueVal'),
  generate: $('generate'),
  loading: $('loading'),
  status: $('status'),
  meta: $('meta'),

  designation: $('designation'),
  designationClass: $('designationClass'),
  dRadius: $('dRadius'),
  dMass: $('dMass'),
  dGrav: $('dGrav'),
  dDay: $('dDay'),
  dAlbedo: $('dAlbedo'),
  dTemp: $('dTemp'),
  dPressure: $('dPressure'),
  compBar: $('compBar'),
  compLegend: $('compLegend'),
  features: $('features'),
  resources: $('resources'),
  exportCard: $('exportCard'),
  dHab: $('dHab'),
  dWater: $('dWater'),

  vpDesignation: $('vpDesignation'),
  vpClass: $('vpClass'),
  vpFrame: $('vpFrame'),
  vpRender: $('vpRender'),

  starsCanvas: $('stars'),
  planetCanvas: $('planet'),
};

export { $, els };
